
import React, { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, CheckCircle2, ClipboardCheck, FileCheck, HardHat, Mail, MapPin, Menu, Phone, Radar, ShieldCheck, X } from "lucide-react";

const PHONE = "(419) 575-1304";
const EMAIL = "Tyler@elevateintegrity.com";

const photos = {
  hero: "/hero.jpg",
  ndt: "/ndt.jpg",
  pipe: "/pipeline.jpg",
  refinery: "/refinery.jpg",
  tech: "/contact.jpg",
};

const nav = [
  ["home", "Home"],
  ["ndt", "NDT Services"],
  ["pipeline", "Pipeline Integrity"],
  ["industries", "Industries & Coverage"],
  ["contact", "Contact"],
];

function Button({ children, className = "", outline = false, ...props }) {
  return <button className={`inline-flex items-center justify-center rounded-xl px-6 py-3 font-bold ${outline ? "border border-white/25 bg-white/5 text-white hover:bg-white/15" : "bg-sky-500 text-white hover:bg-sky-400"} ${className}`} {...props}>{children}</button>;
}

function Header({ page, setPage }) {
  const [open, setOpen] = useState(false);
  const go = (p) => { setPage(p); setOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/90 backdrop-blur-xl">
    <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3">
      <button onClick={() => go("home")} className="flex items-center gap-3 text-left">
        <img src="/elevate-logo.png" alt="Elevate Integrity Services" className="h-14 w-auto" />
        <div className="hidden sm:block"><div className="font-bold text-white">Elevate Integrity Services</div><div className="text-[11px] uppercase tracking-[.22em] text-slate-400">Advanced NDT • MT/PT/RT • Third Party Inspectors</div></div>
      </button>
      <nav className="hidden gap-7 text-sm font-medium text-slate-300 lg:flex">{nav.map(([id,label]) => <button key={id} onClick={() => go(id)} className={page===id ? "text-sky-400" : "hover:text-white"}>{label}</button>)}</nav>
      <a href={`mailto:${EMAIL}`} className="hidden lg:block"><Button outline className="px-4 py-2 text-sm">Request Quote</Button></a>
      <button className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button>
    </div>
    {open && <div className="grid gap-2 border-t border-white/10 bg-slate-950 p-4 lg:hidden">{nav.map(([id,label]) => <button key={id} onClick={() => go(id)} className="rounded-xl bg-white/5 px-4 py-3 text-left text-slate-200">{label}</button>)}</div>}
  </header>
}

function Hero({ setPage }) {
  return <section className="relative min-h-[760px] overflow-hidden">
    <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${photos.hero})` }} />
    <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/35" />
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_20%,rgba(14,165,233,.28),transparent_34%)]" />
    <div className="relative mx-auto grid min-h-[760px] max-w-7xl items-center gap-10 px-6 py-20 md:grid-cols-[1.15fr_.85fr]">
      <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}>
        <div className="mb-6 inline-flex rounded-full border border-sky-300/30 bg-sky-500/10 px-4 py-2 text-sm font-medium text-sky-200">Premium inspection support for critical assets</div>
        <h1 className="max-w-4xl text-5xl font-black leading-[.95] tracking-tight text-white md:text-5xl">Advanced NDT, pipeline integrity, and third-party inspection support — from pipeline systems to terminals, refineries, fabrication, and outage-related projects.</h1>
        <p className="mt-7 max-w-2xl text-lg leading-8 text-slate-200 md:text-xl">Elevate Integrity Services supports pipeline, refinery, station, fabrication, and integrity projects with experienced inspectors, advanced NDT capabilities, clear reporting, and responsive field coverage.</p>
        <div className="mt-9 flex flex-col gap-4 sm:flex-row"><a href={`mailto:${EMAIL}?subject=Inspection Quote Request`}><Button className="w-full py-4 text-base sm:w-auto">Request a Quote <ArrowRight className="ml-2 h-5 w-5" /></Button></a><Button outline onClick={() => setPage("ndt")} className="w-full py-4 text-base sm:w-auto">View Capabilities</Button></div>
      </motion.div>
      <motion.div initial={{opacity:0,x:26}} animate={{opacity:1,x:0}} transition={{duration:.7,delay:.15}} className="rounded-[2rem] border border-white/10 bg-slate-950/70 p-6 shadow-2xl backdrop-blur">
        <img src="/elevate-logo.png" alt="Elevate logo" className="mx-auto mb-6 h-40 w-auto" />
        {["Advanced Service PAUT / TOFD inspection support", "RT / UTSW / VT / MT / PT / Destructive Testing", "Utility, API, CWI, CPWI, and NACE Inspectors", "Clear reporting and field-ready documentation"].map(x => <div key={x} className="mb-3 flex items-center gap-3 rounded-2xl bg-white/[.07] p-4 text-slate-200"><CheckCircle2 className="h-5 w-5 text-sky-400" />{x}</div>)}
      </motion.div>
    </div>
  </section>
}

function ProofStrip(){return <section className="border-y border-white/10 bg-slate-900"><div className="mx-auto grid max-w-7xl px-6 py-8 md:grid-cols-4">{[["Advanced Methods","PAUT • TOFD • AUT • UTSW • CR/DR"],["Pipeline Integrity","ILI digs • SCC • Long seam • RT"],["Field Support","Utility, API, CWI, CPWI, and NACE Inspectors"],["Documentation","Reports • job books • audit support"]].map(([a,b])=><div key={a} className="border-white/10 py-5 md:border-r md:px-7 last:border-r-0"><div className="text-sm uppercase tracking-[.24em] text-sky-400">{a}</div><div className="mt-2 text-lg font-semibold text-white">{b}</div></div>)}</div></section>}

function Home({setPage}){return <><Hero setPage={setPage}/><ProofStrip/><section className="mx-auto max-w-7xl px-6 py-24"><div className="grid gap-14 md:grid-cols-[.9fr_1.1fr] md:items-center"><div className="relative"><img src="/elevate-logo.png" className="h-[520px] w-full rounded-[2rem] object-contain shadow-2xl"/><div className="absolute -bottom-8 -right-5 max-w-sm rounded-3xl border border-white/10 bg-slate-950/90 p-6 shadow-2xl backdrop-blur"><div className="text-sm uppercase tracking-[.24em] text-sky-400">Field First</div><div className="mt-2 text-2xl font-bold text-white">Built for field execution, not just paperwork.</div></div></div><div><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">Core Services</div><h2 className="mt-4 text-4xl font-black tracking-tight text-white md:text-6xl">Inspection support that looks past the checklist.</h2><p className="mt-6 text-lg leading-8 text-slate-300">From routine NDE to advanced ultrasonic inspections, our focus is accurate data, practical answers, and fast turnaround.</p><div className="mt-9 grid gap-4 sm:grid-cols-2">{["Advanced Ultrasonics","Conventional NDT","Pipeline Integrity","Reporting & Job Books"].map(x=><div key={x} className="flex items-center gap-3 border-l-2 border-sky-500 bg-white/[.04] p-4"><ShieldCheck className="h-5 w-5 text-sky-400"/><span className="font-semibold text-white">{x}</span></div>)}</div><button onClick={()=>setPage("ndt")} className="mt-9 inline-flex items-center font-bold text-sky-400 hover:text-sky-300">View NDT capabilities <ArrowRight className="ml-2 h-5 w-5"/></button></div></div></section><Why/><Cta setPage={setPage}/></>}

function Why(){return <section className="bg-slate-900/70 px-6 py-24"><div className="mx-auto max-w-7xl"><div className="mb-12 max-w-3xl"><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">Why Elevate</div><h2 className="mt-4 text-4xl font-black tracking-tight text-white md:text-6xl">Practical inspection experience with a premium standard.</h2></div><div className="grid gap-5 md:grid-cols-4">{[[Radar,"Advanced encoded ultrasonic capability","PAUT, TOFD, long seam, corrosion mapping, and specialized UT inspection support."],[HardHat,"Experienced integrity personnel","Field personnel with practical pipeline, terminal, fabrication, and integrity project experience."],[FileCheck,"Clear client-ready reporting","Clean documentation, inspection summaries, job books, and practical closeout support."],[MapPin,"Responsive regional coverage","Ohio-based support with personnel positioned for Midwest, Northeast, and project-based mobilization."]].map(([Icon,t,d])=><div key={t} className="border border-white/10 bg-slate-950 p-6 hover:border-sky-400/50"><Icon className="mb-8 h-9 w-9 text-sky-400"/><h3 className="text-xl font-bold text-white">{t}</h3><p className="mt-4 leading-7 text-slate-400">{d}</p></div>)}</div></div></section>}

function Interior({eyebrow,title,text,image,children}){return <><section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${image})`}}/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/35"/><div className="relative mx-auto max-w-7xl px-6 py-28 md:py-36"><div className="max-w-4xl"><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">{eyebrow}</div><h1 className="mt-5 text-5xl font-black leading-tight tracking-tight text-white md:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-xl leading-9 text-slate-200">{text}</p></div></div></section><section className="mx-auto max-w-7xl px-6 py-20">{children}</section></>}
function Grid({items}){return <div className="grid gap-5 md:grid-cols-3">{items.map(([t,d])=><div key={t} className="border border-white/10 bg-slate-950 p-7 hover:border-sky-400/60"><ShieldCheck className="mb-7 h-8 w-8 text-sky-400"/><h3 className="text-2xl font-black text-white">{t}</h3><p className="mt-4 leading-7 text-slate-400">{d}</p></div>)}</div>}
function ImageText({image,title,text,reverse}){return <section className="mt-20 grid gap-10 md:grid-cols-2 md:items-center"><img src="/elevate-logo.png" className={`h-[440px] w-full object-contain shadow-2xl ${reverse?'md:order-2':''}`}/><div className={reverse?'md:order-1':''}><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">Field Capability</div><h2 className="mt-4 text-4xl font-black tracking-tight text-white md:text-5xl">{title}</h2><p className="mt-6 text-lg leading-8 text-slate-300">{text}</p></div></section>}

function Ndt(){const items=[["PAUT / TOFD","Advanced ultrasonic inspection for welds, long seam applications, encoded scans, and project-specific inspection needs."],["UT / UTSW / UTT","Conventional ultrasonic weld and thickness inspection for fabrication, maintenance, and integrity support."],["Magnetic Particle Testing","MT inspection for welds, repairs, sleeves, and surface-breaking discontinuities."],["PT / VT / RT", "Liquid penetrant, visual, and radiographic testing support for applicable components, welds, fabrication, and field conditions."],["Corrosion Mapping","Automated and semi-automated ultrasonic data collection for corrosion assessment and documentation."],["Procedure Support","Client-specific procedures, written practices, and inspection documentation support."]];return <Interior eyebrow="NDT Services" title="Advanced and conventional NDT for critical inspection work." text="From routine NDE to advanced ultrasonic inspections, our focus is accurate data, practical answers, and fast turnaround." image={photos.ndt}><Grid items={items}/><ImageText image={photos.tech} title="Built around real field conditions." text="Elevate supports weld inspection, repair verification, fabrication work, terminal projects, pipeline integrity work, and outage-related inspection needs. Our goal is simple: deliver the right inspection method, clean documentation, and field-ready answers."/></Interior>}
function Pipeline(){const items=[["ILI Dig Verification","Field inspection support for anomaly verification, excavation support, documentation, and integrity closeout."],["SCC Validation","Inspection support for stress corrosion cracking programs, documentation, and repair verification."],["Long Seam Inspection","Encoded phased array inspection support for seam assessment and project-specific long seam applications."],["Girth Weld Inspection","Advanced and conventional inspection support for girth weld assessment and repair programs."],["Sleeve / Repair Inspection","MT, VT, UT, and documentation support for sleeves, repairs, and post-repair inspection work."],["Field Oversight","Utility inspection and project oversight support for pipeline integrity campaigns."]];return <Interior eyebrow="Pipeline Integrity" title="Inspection support for integrity digs, SCC, long seam, and field execution." text="Elevate supports pipeline integrity projects with experienced inspectors, advanced NDT capabilities, clear reporting, and responsive field coverage." image={photos.pipe}><Grid items={items}/><ImageText reverse image={photos.refinery} title="Designed for owners, operators, and project teams." text="We support planned work, integrity campaigns, callouts, outage support, and project-based staffing across pipeline, terminal, station, and related industrial assets."/></Interior>}
function Industries(){const items=["Pipeline Integrity","Refineries & Terminals","Fabrication Shops","Compressor & Pump Stations","ILI Verification Digs","Maintenance & Outage Work","Weld Repair Programs","Owner Representation"];return <Interior eyebrow="Industries & Coverage" title="Inspection support for critical infrastructure." text="Based in Ohio with inspection personnel positioned across multiple regions, Elevate supports projects throughout the Midwest, Northeast, and beyond when project scope requires it." image={photos.refinery}><div className="grid gap-4 md:grid-cols-4">{items.map(x=><div key={x} className="border border-white/10 bg-slate-950 p-6 text-lg font-bold text-white">{x}</div>)}</div><section className="mt-20 grid gap-10 border border-white/10 bg-slate-900 p-8 md:grid-cols-[1fr_1.1fr] md:p-12"><div><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">Coverage</div><h2 className="mt-4 text-4xl font-black tracking-tight text-white">Strategically positioned for responsive field support.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-300"><p>Based in Dover, Ohio, Elevate is positioned to support pipeline, terminal, station, fabrication, maintenance, and integrity work throughout key operating regions.</p><div className="rounded-2xl bg-slate-950 p-6">Available for planned work, integrity campaigns, callouts, outage support, and project-based staffing.</div></div></section></Interior>}
function Contact(){return <Interior eyebrow="Contact" title="Need inspection support?" text="Send the scope, location, schedule, and required method. We’ll help clarify the request and build a practical quote." image={photos.tech}><section className="grid gap-8 md:grid-cols-[.9fr_1.1fr]"><div className="border border-white/10 bg-slate-950 p-8"><h2 className="text-3xl font-black text-white">Start a Quote</h2><p className="mt-4 leading-7 text-slate-400">For faster pricing, include project location, inspection method, schedule, estimated duration, site requirements, and any client-specific reporting needs.</p><div className="mt-8 space-y-5"><a href={`tel:${PHONE.replace(/[^0-9]/g,"")}`} className="flex items-center gap-4 text-lg font-semibold text-white hover:text-sky-400"><Phone className="h-6 w-6 text-sky-400"/>{PHONE}</a><a href={`mailto:${EMAIL}`} className="flex items-center gap-4 text-lg font-semibold text-white hover:text-sky-400"><Mail className="h-6 w-6 text-sky-400"/>{EMAIL}</a><div className="flex items-center gap-4 text-lg font-semibold text-white"><MapPin className="h-6 w-6 text-sky-400"/>Dover, Ohio</div></div></div><div className="border border-white/10 bg-slate-900 p-8"><div className="text-sm font-bold uppercase tracking-[.25em] text-sky-400">Quote Request Details</div><div className="mt-6 grid gap-4">{["Project name and location","Required inspection method","Estimated start date and duration","Site access and safety requirements","Reporting or documentation requirements","Applicable code, procedure, or client standard"].map(x=><div key={x} className="flex items-center gap-3 rounded-xl bg-slate-950 p-4 text-slate-200"><ClipboardCheck className="h-5 w-5 text-sky-400"/>{x}</div>)}</div><a href={`mailto:${EMAIL}?subject=Inspection Quote Request`} className="mt-7 block"><Button className="w-full py-4 text-base">Email Quote Request</Button></a></div></section></Interior>}
function Cta({setPage}){return <section className="px-6 py-24"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-r from-sky-600 to-slate-900 p-10 shadow-2xl md:p-14"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="text-4xl font-black tracking-tight text-white md:text-5xl">Need inspection support?</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-sky-50">Send the scope, location, schedule, and required method. We’ll help clarify the request and build a practical quote.</p></div><Button onClick={()=>setPage("contact")} className="bg-white px-8 py-4 text-slate-950 hover:bg-slate-100">Contact Elevate <ArrowRight className="ml-2 h-5 w-5"/></Button></div></div></section>}
function Footer({setPage}){return <footer className="border-t border-white/10 bg-slate-950 px-6 py-10"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1.2fr_.8fr_.8fr]"><div><img src="/elevate-logo.png" className="mb-5 h-20 w-auto"/><p className="max-w-xl leading-7 text-slate-400">Advanced NDT, PAUT, TOFD, pipeline integrity, utility inspection, and field oversight support.</p></div><div><div className="mb-4 font-bold text-white">Pages</div><div className="grid gap-2 text-slate-400">{nav.map(([id,label])=><button key={id} onClick={()=>setPage(id)} className="text-left hover:text-sky-400">{label}</button>)}</div></div><div><div className="mb-4 font-bold text-white">Contact</div><div className="grid gap-3 text-slate-400"><a href={`tel:${PHONE.replace(/[^0-9]/g,"")}`} className="hover:text-sky-400">{PHONE}</a><a href={`mailto:${EMAIL}`} className="hover:text-sky-400">{EMAIL}</a><div>Dover, Ohio</div></div></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-sm text-slate-500">© 2026 Elevate Integrity Services. All rights reserved.</div></footer>}
export default function App(){const [page,setPage]=useState("home");return <div className="min-h-screen bg-slate-950 text-white"><Header page={page} setPage={setPage}/>{page==="ndt"?<Ndt/>:page==="pipeline"?<Pipeline/>:page==="industries"?<Industries/>:page==="contact"?<Contact/>:<Home setPage={setPage}/>}<Footer setPage={setPage}/></div>}
